# -*- coding: utf-8 -*-
"""Momentum_Based_Strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12D-13ItPkArcmsvdbTpyIZ6M2fwyl88D
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf

raw=yf.download('^XAU',start="2013-01-01",end="2023-01-01")
data=pd.DataFrame(raw)
data.head()

data['Returns']=np.log(data['Close']/data['Close'].shift(1))
data['Returns']

data['position']=np.sign(data['Returns'].rolling(3).mean())
data['strategy']=data['position'].shift(1)*data['Returns']
data['strategy']

data[['Returns','strategy']].dropna().cumsum().apply(np.exp).plot(figsize=(10,6))

initial_investment = 1000

# Calculate cumulative returns (growth factor)
cumulative_growth = data['strategy'].dropna().cumsum().apply(np.exp)
print(cumulative_growth)

# Calculate portfolio value over time by multiplying by initial investment
portfolio_value = initial_investment * cumulative_growth



# Plot portfolio value
portfolio_value.plot(figsize=(10,6), title='Strategy Portfolio Value Over Time')
plt.ylabel('Portfolio Value ($)')
plt.show()